// UI helpers: ISO country codes (for SVG flags) + 3-letter football codes.
// Purely presentational — falls back gracefully for unknown teams.

const TEAMS: Record<string, [iso: string, code: string]> = {
  Albania: ["al", "ALB"],
  Algeria: ["dz", "ALG"],
  Argentina: ["ar", "ARG"],
  Armenia: ["am", "ARM"],
  Australia: ["au", "AUS"],
  Austria: ["at", "AUT"],
  Azerbaijan: ["az", "AZE"],
  Bahrain: ["bh", "BHR"],
  Bangladesh: ["bd", "BAN"],
  Belarus: ["by", "BLR"],
  Belgium: ["be", "BEL"],
  Bolivia: ["bo", "BOL"],
  "Bosnia and Herzegovina": ["ba", "BIH"],
  Brazil: ["br", "BRA"],
  Brunei: ["bn", "BRU"],
  Bulgaria: ["bg", "BUL"],
  Cambodia: ["kh", "CAM"],
  Cameroon: ["cm", "CMR"],
  Canada: ["ca", "CAN"],
  "Cape Verde": ["cv", "CPV"],
  Chile: ["cl", "CHI"],
  China: ["cn", "CHN"],
  Colombia: ["co", "COL"],
  "Costa Rica": ["cr", "CRC"],
  Croatia: ["hr", "CRO"],
  Curacao: ["cw", "CUW"],
  "Czech Republic": ["cz", "CZE"],
  Czechia: ["cz", "CZE"],
  Denmark: ["dk", "DEN"],
  Ecuador: ["ec", "ECU"],
  Egypt: ["eg", "EGY"],
  England: ["gb-eng", "ENG"],
  Estonia: ["ee", "EST"],
  Finland: ["fi", "FIN"],
  France: ["fr", "FRA"],
  Georgia: ["ge", "GEO"],
  Germany: ["de", "GER"],
  Ghana: ["gh", "GHA"],
  Greece: ["gr", "GRE"],
  Guatemala: ["gt", "GUA"],
  Haiti: ["ht", "HAI"],
  Honduras: ["hn", "HON"],
  "Hong Kong": ["hk", "HKG"],
  Hungary: ["hu", "HUN"],
  Iceland: ["is", "ISL"],
  India: ["in", "IND"],
  Indonesia: ["id", "IDN"],
  Iran: ["ir", "IRN"],
  Iraq: ["iq", "IRQ"],
  Ireland: ["ie", "IRL"],
  Israel: ["il", "ISR"],
  Italy: ["it", "ITA"],
  "Ivory Coast": ["ci", "CIV"],
  Jamaica: ["jm", "JAM"],
  Japan: ["jp", "JPN"],
  Jordan: ["jo", "JOR"],
  Kazakhstan: ["kz", "KAZ"],
  Kenya: ["ke", "KEN"],
  Kuwait: ["kw", "KUW"],
  Laos: ["la", "LAO"],
  Latvia: ["lv", "LVA"],
  Lebanon: ["lb", "LBN"],
  Lithuania: ["lt", "LTU"],
  Luxembourg: ["lu", "LUX"],
  Malaysia: ["my", "MAS"],
  Mali: ["ml", "MLI"],
  Malta: ["mt", "MLT"],
  Mexico: ["mx", "MEX"],
  Moldova: ["md", "MDA"],
  Mongolia: ["mn", "MNG"],
  Montenegro: ["me", "MNE"],
  Morocco: ["ma", "MAR"],
  Myanmar: ["mm", "MYA"],
  Nepal: ["np", "NEP"],
  Netherlands: ["nl", "NED"],
  "New Zealand": ["nz", "NZL"],
  Nigeria: ["ng", "NGA"],
  "North Macedonia": ["mk", "MKD"],
  Norway: ["no", "NOR"],
  Oman: ["om", "OMA"],
  Pakistan: ["pk", "PAK"],
  Panama: ["pa", "PAN"],
  Paraguay: ["py", "PAR"],
  Peru: ["pe", "PER"],
  Philippines: ["ph", "PHI"],
  Poland: ["pl", "POL"],
  Portugal: ["pt", "POR"],
  Qatar: ["qa", "QAT"],
  Romania: ["ro", "ROU"],
  Russia: ["ru", "RUS"],
  "Saudi Arabia": ["sa", "KSA"],
  Scotland: ["gb-sct", "SCO"],
  Senegal: ["sn", "SEN"],
  Serbia: ["rs", "SRB"],
  Singapore: ["sg", "SGP"],
  Slovakia: ["sk", "SVK"],
  Slovenia: ["si", "SVN"],
  "South Africa": ["za", "RSA"],
  "South Korea": ["kr", "KOR"],
  Spain: ["es", "ESP"],
  "Sri Lanka": ["lk", "SRI"],
  Sweden: ["se", "SWE"],
  Switzerland: ["ch", "SUI"],
  Taiwan: ["tw", "TPE"],
  Tajikistan: ["tj", "TJK"],
  Thailand: ["th", "THA"],
  "Timor-Leste": ["tl", "TLS"],
  Tunisia: ["tn", "TUN"],
  Turkey: ["tr", "TUR"],
  Turkmenistan: ["tm", "TKM"],
  Ukraine: ["ua", "UKR"],
  "United Arab Emirates": ["ae", "UAE"],
  "United States": ["us", "USA"],
  Uruguay: ["uy", "URU"],
  Uzbekistan: ["uz", "UZB"],
  Venezuela: ["ve", "VEN"],
  Vietnam: ["vn", "VIE"],
  Wales: ["gb-wls", "WAL"],
  Yemen: ["ye", "YEM"],
  Zambia: ["zm", "ZAM"],
  Zimbabwe: ["zw", "ZIM"],
};

/** ISO 3166 code for flag images, or null when unknown. */
export function iso(team: string): string | null {
  return TEAMS[team]?.[0] ?? null;
}

export function code(team: string): string {
  if (TEAMS[team]) return TEAMS[team][1];
  return team.replace(/[^A-Za-z]/g, "").slice(0, 3).toUpperCase() || "TBD";
}
